<?php

use Illuminate\Database\Seeder;

class AdminMenuTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        \DB::table('admin_menu')->truncate();

        \DB::table('admin_menu')->insert([
            
            [
                'id'             => 2,
                'parent_id'           => '0',    
                'order'           => 2,    
                'title'           => '管理员',    
                'icon'           => 'fa-tasks',    
                'uri'           => '',    
                'permission'           => '',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 3,
                'parent_id'           => '2',    
                'order'           => 3,    
                'title'           => '用户',    
                'icon'           => 'fa-users',    
                'uri'           => '/auth/users',    
                'permission'           => '',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 4,
                'parent_id'           => '2',    
                'order'           => 4,    
                'title'           => '规则',    
                'icon'           => 'fa-user',    
                'uri'           => '/auth/roles',    
                'permission'           => '',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 5,
                'parent_id'           => '2',    
                'order'           => 5,    
                'title'           => '允许',    
                'icon'           => 'fa-ban',    
                'uri'           => '/auth/permissions',    
                'permission'           => '',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 6,
                'parent_id'           => '2',    
                'order'           =>  6,    
                'title'           => '菜单',    
                'icon'           => 'fa-bars',    
                'uri'           => '/auth/menu',    
                'permission'           => '',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 7,
                'parent_id'           => '2',    
                'order'           => 7,    
                'title'           => '经营历史',    
                'icon'           => 'fa-history',    
                'uri'           => '/auth/logs',    
                'permission'           => '',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 8,
                'parent_id'           => '0',    
                'order'           => 8,    
                'title'           => '房间管理',    
                'icon'           => 'fa-bars',    
                'uri'           => '/room',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 9,
                'parent_id'           => '8',    
                'order'           => 9,    
                'title'           => '界面配置',    
                'icon'           => 'fa-bars',    
                'uri'           => '/room/power',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 10,
                'parent_id'           => '8',    
                'order'           => 10,    
                'title'           => '权限配置',    
                'icon'           => 'fa-bars',    
                'uri'           => '/room',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 11,
                'parent_id'           => '0',    
                'order'           => 11,    
                'title'           => '消息管理',    
                'icon'           => 'fa-wechat',    
                'uri'           => '/chatmng',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 12,
                'parent_id'           => '0',    
                'order'           => 12,    
                'title'           => '数据分析',    
                'icon'           => 'fa-bar-chart',    
                'uri'           => '/chartmng',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 13,
                'parent_id'           => '0',    
                'order'           => 13,    
                'title'           => '客服管理',    
                'icon'           => 'fa-cogs',    
                'uri'           => '/qq',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 14,
                'parent_id'           => '0',    
                'order'           => 14,    
                'title'           => '客服管理',    
                'icon'           => 'fa-television',    
                'uri'           => '/nav',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 15,
                'parent_id'           => '0',    
                'order'           => 15,    
                'title'           => '客服管理',    
                'icon'           => 'fa-android',    
                'uri'           => '/file',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 16,
                'parent_id'           => '0',    
                'order'           => 0,    
                'title'           => '用户管理',    
                'icon'           => 'fa-users',    
                'uri'           => '/user',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 17,
                'parent_id'           => '16',    
                'order'           => 0,    
                'title'           => '用户列表',    
                'icon'           => 'fa-bars',    
                'uri'           => '/user',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 18,
                'parent_id'           => '16',    
                'order'           => 0,    
                'title'           => '密码',    
                'icon'           => 'fa-eye',    
                'uri'           => '/password',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ],
            [
                'id'             => 19,
                'parent_id'           => '16',    
                'order'           => 0,    
                'title'           => '在线用户',    
                'icon'           => 'fa-headphones',    
                'uri'           => '/online',    
                'permission'           => '*',   
                'created_at'   => \Carbon\Carbon::now()->toDateTimeString(),
                'updated_at'   => \Carbon\Carbon::now()->toDateTimeString(),     
            ]
        ]);
    }
}
